using System;
namespace Dangl.GiteaOrgManager
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionInfo
    {
        public static string Version => "0.1.5";
        public static string CommitInfo => "Branch.master.Sha.b3ca196089173ec63e9a33461c36aca71d01eb83";
        public static string CommitDate => "2023-06-23";
        public static string CommitHash => "b3ca196089173ec63e9a33461c36aca71d01eb83";
        public static string InformationalVersion => "0.1.5+Branch.master.Sha.b3ca196089173ec63e9a33461c36aca71d01eb83";
        public static DateTime BuildDateUtc => new DateTime(2023, 6, 23, 12, 53, 14, DateTimeKind.Utc);
    }
}
